Repository wri/gfw, pull requests merged in 2018-08, with the labels that each got.

#3530 [FIRES STATS] Updates latest date
  app/javascript/components/widgets/widgets/forest-change/fires-alerts/selectors.js
Labels: dashboards

#3538 Updates land cover widget metadata key
  app/javascript/components/widgets/widgets/land-cover/global-land-cover/initial-state.js
Labels: _DEPLOY

#3540 Feature/layer interactions
  app/javascript/components/map/components/legend/components/layer-selector-menu/component.jsx
  app/javascript/components/map/components/legend/components/layer-selector-menu/index.js
  app/javascript/components/map/components/legend/components/layer-selector-menu/selectors.js
  app/javascript/components/map/components/legend/components/layer-selector-menu/styles.scss
  app/javascript/components/map/components/legend/components/layer-toggle/component.jsx
  app/javascript/components/map/components/legend/components/timeline/component.js
  app/javascript/components/map/components/legend/components/timeline/index.js
  app/javascript/components/map/components/legend/components/timeline/styles.scss
  app/javascript/components/map/components/legend/legend-component.jsx
  app/javascript/components/map/components/legend/legend-styles.scss
  app/javascript/components/map/components/legend/legend.js
  app/javascript/components/map/components/popup/actions.js
  app/javascript/components/map/components/popup/component.js
  app/javascript/components/map/components/popup/components/data-table/component.jsx
  app/javascript/components/map/components/popup/components/data-table/index.js
  app/javascript/components/map/components/popup/components/data-table/styles.scss
  app/javascript/components/map/components/popup/popup.js
  app/javascript/components/map/components/popup/reducers.js
  app/javascript/components/map/components/popup/selectors.js
  app/javascript/components/map/components/popup/styles.scss
  app/javascript/components/map/map-component.js
  app/javascript/components/map/map-selectors.js
  app/javascript/components/ui/card/card-component.jsx
  app/javascript/components/ui/card/card-styles.scss
  app/javascript/components/ui/card/themes/card-small.scss
  app/javascript/components/ui/dropdown/dropdown-component.jsx
  app/javascript/components/ui/dropdown/themes/dropdown-native-plain.scss
  app/javascript/components/ui/slider/slider-component.js
  app/javascript/components/ui/slider/styles.scss
  app/javascript/components/ui/slider/themes/slider-green.scss
  app/javascript/pages/map/menu/components/sections/explore/explore-component.jsx
  app/javascript/pages/map/menu/menu-selectors.js
  app/javascript/providers/datasets-provider/datasets-provider-actions.js
  package.json
  yarn-error.log
  yarn.lock
Labels: map

#3500 Add new RSPO oil palm layer to Land Use tab
  app/assets/javascripts/map/cartocss/rspo.cartocss
  app/assets/javascripts/map/helpers/layersHelper.js
  app/assets/javascripts/map/models/LayerSpecModel.js
  app/assets/javascripts/map/templates/infowindow.handlebars
  app/assets/javascripts/map/templates/layersNav.handlebars
  app/assets/javascripts/map/templates/legend/rspo.handlebars
  app/assets/javascripts/map/views/LegendView.js
  app/assets/javascripts/map/views/layers/RSPOLayer.js
Labels: map

#3554 fixed bug on active fires analysis service
  app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
Labels: analysis, bugs

#3556 Calculates natural forest for header in plantations countries
  app/javascript/pages/dashboards/header/header-actions.js
  app/javascript/pages/dashboards/header/header-reducers.js
  app/javascript/pages/dashboards/header/header-selectors.js
Labels: _DEPLOY, countries dashboard

#3559 Adds IDN-specific header sentence
  app/javascript/pages/dashboards/header/header-actions.js
  app/javascript/pages/dashboards/header/header-reducers.js
  app/javascript/pages/dashboards/header/header-selectors.js
Labels: _DEPLOY

#3572 Feature/new icons and map controls update
  app/assets/images/layer-icons/binos.png
  app/assets/images/layer-icons/binos.svg
  app/javascript/assets/icons/analysis.svg
  app/javascript/assets/icons/biodiversity.svg
  app/javascript/assets/icons/chevron-left.svg
  app/javascript/assets/icons/click-map.svg
  app/javascript/assets/icons/climate-bubbles.svg
  app/javascript/assets/icons/climate.svg
  app/javascript/assets/icons/download.svg
  app/javascript/assets/icons/drag.svg
  app/javascript/assets/icons/draw-on-map.svg
  app/javascript/assets/icons/explore.svg
  app/javascript/assets/icons/feather.svg
  app/javascript/assets/icons/fit-zoom.svg
  app/javascript/assets/icons/forest-change.svg
  app/javascript/assets/icons/hidden.svg
  app/javascript/assets/icons/land-cover.svg
  app/javascript/assets/icons/land-tree.svg
  app/javascript/assets/icons/land-use.svg
  app/javascript/assets/icons/layers.svg
  app/javascript/assets/icons/minus.svg
  app/javascript/assets/icons/pause.svg
  app/javascript/assets/icons/places-to-watch.svg
  app/javascript/assets/icons/play.svg
  app/javascript/assets/icons/plus.svg
  app/javascript/assets/icons/print.svg
  app/javascript/assets/icons/satellite.svg
  app/javascript/assets/icons/search.svg
  app/javascript/assets/icons/settings.svg
  app/javascript/assets/icons/share.svg
  app/javascript/assets/icons/transparency.svg
  app/javascript/assets/icons/truck.svg
  app/javascript/assets/icons/visible.svg
  app/javascript/components/map-v2/component.js
  app/javascript/components/map-v2/components/legend/components/timeline/styles.scss
  app/javascript/components/map-v2/components/legend/legend-component.jsx
  app/javascript/components/map-v2/components/legend/legend.js
  app/javascript/components/map-v2/components/map-controls/map-controls-component.jsx
  app/javascript/components/map-v2/components/map-controls/map-controls-styles.scss
  app/javascript/components/map-v2/initial-state.js
  app/javascript/components/map-v2/selectors.js
  app/javascript/components/map-v2/styles.scss
  app/javascript/pages/map-v2/menu/menu-sections.js
  app/javascript/pages/map-v2/menu/menu-styles.scss
  app/javascript/pages/map-v2/page/page-component.js
  app/javascript/pages/map-v2/page/page-styles.scss
  app/javascript/pages/map-v2/page/page.js
Labels: staging

#3573 Feature/new header
  app/javascript/assets/icons/blog.svg
  app/javascript/assets/icons/contribute.svg
  app/javascript/assets/icons/developer.svg
  app/javascript/assets/icons/forum.svg
  app/javascript/assets/icons/howto.svg
  app/javascript/assets/icons/menu.svg
  app/javascript/assets/icons/more.svg
  app/javascript/assets/icons/mygfw.svg
  app/javascript/assets/icons/open-data.svg
  app/javascript/assets/icons/sgf.svg
  app/javascript/assets/icons/stories.svg
  app/javascript/assets/logos/gfw-climate.png
  app/javascript/assets/logos/gfw-commodities.png
  app/javascript/assets/logos/gfw-fires.png
  app/javascript/assets/logos/gfw-watcher.png
  app/javascript/assets/logos/gfw-water.png
  app/javascript/components/header/component.jsx
  app/javascript/components/header/components/dropdown-menu/component.jsx
  app/javascript/components/header/components/dropdown-menu/index.js
  app/javascript/components/header/components/dropdown-menu/styles.scss
  app/javascript/components/header/components/mygfw-login/component.jsx
  app/javascript/components/header/components/mygfw-login/index.js
  app/javascript/components/header/components/mygfw-login/styles.scss
  app/javascript/components/header/components/submenu-panel/component.jsx
  app/javascript/components/header/components/submenu-panel/index.js
  app/javascript/components/header/components/submenu-panel/styles.scss
  app/javascript/components/header/config.js
  app/javascript/components/header/index.js
  app/javascript/components/header/styles.scss
  app/javascript/components/map-v2/components/legend/components/timeline/styles.scss
  app/javascript/components/ui/search/search-component.jsx
  app/javascript/components/ui/search/search-styles.scss
  app/javascript/pages/map-v2/menu/menu-component.jsx
  app/javascript/pages/map-v2/menu/menu-styles.scss
  app/javascript/pages/map-v2/page/page-component.js
  app/javascript/pages/map-v2/page/page-styles.scss
  app/javascript/pages/map-v2/page/page.js
  app/javascript/pages/map-v2/store.js
  app/javascript/pages/sgf/section-projects/section-projects.js
  app/javascript/providers/mygfw-provider/actions.js
  app/javascript/providers/mygfw-provider/index.js
  app/javascript/providers/mygfw-provider/reducers.js
  app/javascript/styles/text.scss
Labels: staging

#3575 Feature/reduce map selectors for performance
  app/javascript/components/map-v2/component.js
  app/javascript/components/map-v2/components/basemaps/basemaps-component.jsx
  app/javascript/components/map-v2/components/basemaps/basemaps-schema.js
  app/javascript/components/map-v2/components/basemaps/basemaps.js
  app/javascript/components/map-v2/components/legend/components/layer-statement/config.js
  app/javascript/components/map-v2/components/legend/components/layer-statement/index.js
  app/javascript/components/map-v2/components/legend/legend-component.jsx
  app/javascript/components/map-v2/components/legend/legend-styles.scss
  app/javascript/components/map-v2/components/legend/legend.js
  app/javascript/components/map-v2/components/popup/component.js
  app/javascript/components/map-v2/components/popup/popup.js
  app/javascript/components/map-v2/components/popup/selectors.js
  app/javascript/components/map-v2/components/popup/styles.scss
  app/javascript/components/map-v2/index.js
  app/javascript/components/map-v2/initial-state.js
  app/javascript/components/map-v2/selectors.js
  app/javascript/components/ui/card/card-component.jsx
  app/javascript/pages/map-v2/data-analysis-menu/data-analysis-menu.js
  app/javascript/pages/map-v2/index.js
  app/javascript/pages/map-v2/menu/menu-selectors.js
  app/javascript/pages/map-v2/menu/menu.js
  app/javascript/pages/map-v2/page/page-component.js
  app/javascript/pages/map-v2/page/page.js
  app/javascript/pages/map-v2/store.js
  app/javascript/providers/datasets-provider/datasets-decode-config.js
  app/javascript/providers/datasets-provider/datasets-provider-actions.js
  app/javascript/providers/datasets-provider/datasets-utils.js
  app/javascript/providers/latest-provider/actions.js
  app/javascript/providers/latest-provider/index.js
  app/javascript/providers/latest-provider/reducers.js
  app/javascript/styles/styles.scss
  package.json
  yarn.lock
Labels: staging

#3574 [MAP ANALYSIS] Increase polygon complexity for 'small' countries
  app/assets/javascripts/services/CountryService.js
  package.json
  yarn.lock
Labels: HOTFIX, _DEPLOY

#3571 Fixed Tree Cover Pies
  app/javascript/components/widgets/widgets/land-cover/tree-cover/actions.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
Labels: staging
