Repository wri/gfw, pull requests merged in 2018-07, with the labels that each got.

#3506 Allows all forest change layers to be used in analysis
  app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
  app/assets/javascripts/map/services/AnalysisNewService.js
  app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
Labels: analysis, map

#3515 [Dashboards]: Fixes unit issue in employment pie-chart legend
  app/javascript/components/widgets/components/widget-pie-chart-legend/component.jsx
  app/javascript/components/widgets/widgets/people/forestry-employment/initial-state.js
Labels: _DEPLOY

#3394 Feature/ind land cover
  app/assets/javascripts/map/cartocss/idn_land_cover.cartocss
  app/assets/javascripts/map/helpers/layersHelper.js
  app/assets/javascripts/map/models/LayerSpecModel.js
  app/assets/javascripts/map/templates/legend/idn_land_cover.handlebars
  app/assets/javascripts/map/views/LegendView.js
  app/assets/javascripts/map/views/layers/IdnLandCoverLayer.js
Labels: map

#3516 Changed table sources to point at gadm3.6 tables in the API
  app/assets/javascripts/services/CountryService.js
Labels: bugs, map

#3522 [ANALYSIS] Parses response data correctly
  app/assets/javascripts/map/services/AnalysisNewService.js
Labels: _DEPLOY

#3519 Forestry employment widget: missing multiplication factor
  app/javascript/components/widgets/widgets/people/forestry-employment/selectors.js
Labels: bugs, countries dashboard

#3520 [Country Dashboards] Ranking statement calculation fix
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
Labels: _DEPLOY, dashboards

#3523 [ANALYSIS]: Fixes loss & multiple analyses
  app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
  app/assets/javascripts/map/services/AnalysisNewService.js
Labels: _DEPLOY, bugs

#3526 Updated fires whitelist
  app/javascript/components/widgets/widgets/forest-change/fires-alerts/initial-state.js
Labels: countries dashboard

#3524 Feature/primary forest updates
  app/assets/javascripts/map/helpers/layersHelper.js
  app/assets/javascripts/map/models/LayerSpecModel.js
  app/assets/javascripts/map/templates/layersNav.handlebars
  app/assets/javascripts/map/views/layers/PrimaryForestLayer.js
Labels: map

#3532 Added subtitle to primary forests
  app/assets/javascripts/map/templates/layersNav.handlebars
Labels: map
