Repository wri/gfw, pull requests merged in 2018-06, with the labels that each got.

#3455 Global 100%
  app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
Labels: staging

#3457 Updates gain widgets
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
Labels: staging

#3461 Feedback implementation
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
  app/javascript/pages/dashboards/header/header-reducers.js
Labels: _DEPLOY

#3466 Minor Feedback Updates
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
  app/javascript/pages/dashboards/header/header-selectors.js
Labels: HOTFIX, _DEPLOY

#3468 Fixes Emissions Calculations in Natural Forest Loss widget
  app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/selectors.js
  app/javascript/pages/dashboards/header/header-selectors.js
Labels: _DEPLOY

#3469 Added Landsat 2017 to the basemaps
  app/assets/javascripts/map/templates/maptype.handlebars
  app/assets/javascripts/map/templates/tabs/basemaps.handlebars
  app/assets/javascripts/map/views/MapView.js
  app/assets/javascripts/map/views/maptypes/landsatMaptype.js
Labels: map

#3470 Fixes GLAD ranking queries
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
  app/javascript/services/alerts.js
  app/javascript/services/forest-data.js
  app/javascript/utils/strings.js
Labels: _DEPLOY

#3477 Feature: global disclaimer to footer of widgets
  app/javascript/components/widgets/actions.js
  app/javascript/components/widgets/components/widget-footer/component.jsx
  app/javascript/components/widgets/components/widget-footer/selectors.js
  app/javascript/components/widgets/components/widget-footer/styles.scss
  app/javascript/components/widgets/components/widget-footer/widget-footer.js
  app/javascript/components/widgets/components/widget-settings-statement/widget-settings-statement-component.jsx
  app/javascript/components/widgets/components/widget-settings-statement/widget-settings-statement-selectors.js
  app/javascript/components/widgets/components/widget/component.jsx
  app/javascript/components/widgets/components/widget/widget.js
  app/javascript/components/widgets/reducers.js
  app/javascript/components/widgets/widgets.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-global/selectors.js
  app/javascript/services/forest-data.js
Labels: staging

#3471 updated the IFL layer
  app/assets/javascripts/map/cartocss/intact2013.cartocss
  app/assets/javascripts/map/templates/layersNav.handlebars
  app/assets/javascripts/map/templates/legend/intact2013.handlebars
Labels: map

#3439 Update loss layer to have 2017 data
  app/assets/javascripts/map/views/layers/LossLayer.js
Labels: WIP, staging

#3479 Feature/settings new design
  app/javascript/components/ui/dropdown/dropdown-styles.scss
  app/javascript/components/ui/dropdown/themes/dropdown-button.scss
  app/javascript/components/ui/switch/react-toggle.scss
  app/javascript/components/ui/switch/switch-component.jsx
  app/javascript/components/ui/switch/switch-styles.scss
  app/javascript/components/ui/switch/switch.js
  app/javascript/components/ui/switch/themes/switch-light.scss
  app/javascript/components/widgets/components/widget-settings/widget-settings-component.jsx
  app/javascript/components/widgets/components/widget-settings/widget-settings-styles.scss
  package.json
Labels: staging

#3489 Places To Watch: Update sql
  app/assets/javascripts/map/views/layers/Places2WatchLayer.js
Labels: _DEPLOY

#3473 Feature: abstract caching helper to request level to make code simpler
  .travis.yml
  app/controllers/application_controller.rb
  app/javascript/components/map/map.js
  app/javascript/pages/dashboards/embed/embed-component.js
  app/javascript/pages/dashboards/header/header-reducers.js
  app/javascript/pages/dashboards/header/header.js
  app/javascript/pages/dashboards/index.js
  app/javascript/pages/dashboards/page/page-component.js
  app/javascript/pages/dashboards/page/page.js
  app/javascript/pages/dashboards/reducers.js
  app/javascript/providers/cache-provider/cache-provider-actions.js
  app/javascript/providers/cache-provider/cache-provider-reducers.js
  app/javascript/providers/cache-provider/cache-provider.js
  app/javascript/providers/country-data-provider/country-data-provider.js
  app/javascript/providers/whitelists-provider/whitelists-provider.js
  app/javascript/services/cache.js
  app/javascript/utils/request.js
  app/views/layouts/application_react.html.erb
  app/views/shared/_cache_keys.html.erb
Labels: WIP

#3491 GADM36: Table updates & Country fetches
  app/assets/javascripts/services/CountryService.js
  app/javascript/providers/country-data-provider/country-data-provider-actions.js
  app/javascript/services/country.js
  app/javascript/services/total-area.js
  app/javascript/services/whitelists.js
  app/javascript/utils/format.js
Labels: gadm36

#3498 GADM36: Update Analysis to /v3/
  app/assets/javascripts/map/services/AnalysisNewService.js
Labels: gadm36

#3497 Feature/map menu
  app/javascript/assets/icons/climate-bubbles.svg
  app/javascript/assets/icons/feather.svg
  app/javascript/assets/icons/land-tree.svg
  app/javascript/assets/icons/trees.svg
  app/javascript/assets/icons/truck.svg
  app/javascript/assets/icons/world.svg
  app/javascript/assets/logos/gfw.png
  app/javascript/components/ui/button/button-component.jsx
  app/javascript/components/ui/button/themes/button-tiny.scss
  app/javascript/components/ui/switch/switch-component.jsx
  app/javascript/components/ui/switch/themes/switch-toggle.scss
  app/javascript/pages/map/menu/components/forest-change/forest-change-component.jsx
  app/javascript/pages/map/menu/components/forest-change/forest-change.js
  app/javascript/pages/map/menu/components/layer-toggle/layer-toggle-component.jsx
  app/javascript/pages/map/menu/components/layer-toggle/layer-toggle-styles.scss
  app/javascript/pages/map/menu/components/layer-toggle/layer-toggle.js
  app/javascript/pages/map/menu/components/layers-block/layers-block-component.jsx
  app/javascript/pages/map/menu/components/layers-block/layers-block-styles.scss
  app/javascript/pages/map/menu/components/layers-block/layers-block.js
  app/javascript/pages/map/menu/menu-actions.js
  app/javascript/pages/map/menu/menu-component.jsx
  app/javascript/pages/map/menu/menu-reducers.js
  app/javascript/pages/map/menu/menu-selectors.js
  app/javascript/pages/map/menu/menu-styles.scss
  app/javascript/pages/map/menu/menu.js
  app/javascript/pages/map/page/page-component.js
  app/javascript/pages/map/page/page.js
  app/javascript/pages/map/reducers.js
  app/javascript/styles/settings.scss
Labels: WIP, map

#3499 Feature/new indicators for widgets
  app/javascript/components/ui/switch/react-toggle.scss
  app/javascript/components/widgets/components/widget-settings/widget-settings-component.jsx
  app/javascript/components/widgets/components/widget-settings/widget-settings-styles.scss
  app/javascript/components/widgets/components/widget/selectors.js
  app/javascript/components/widgets/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions-deforestation/initial-state.js
  app/javascript/components/widgets/widgets/conservation/glad-biodiversity/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/primary-forest/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
  app/javascript/data/forest-types.json
  app/javascript/data/land-categories.json
  app/javascript/services/forest-data.js
Labels: AWAITING APPROVAL, WIP, gadm36

#3481 Feature/2017 loss
  app/assets/javascripts/map/views/layers/LossLayer.js
  app/javascript/components/map/assets/layers/loss.js
  app/javascript/components/widgets/widgets/climate/emissions-deforestation/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-global/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss/selectors.js
  app/javascript/pages/dashboards/header/header.js
Labels: 2017-tree-loss, WIP, staging

#3496 Feature: GADM36 on GFW
  app/assets/javascripts/map/presenters/analysis/AnalysisCountryPresenter.js
  app/assets/javascripts/map/presenters/analysis/AnalysisResultsNewPresenter.js
  app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js
  app/assets/javascripts/map/services/AnalysisNewService.js
  app/assets/javascripts/map/services/AnalysisService.js
  app/assets/javascripts/map/services/GeostoreService.js
  app/assets/javascripts/map/templates/analysis/analysis-results.handlebars
  app/assets/javascripts/map/views/analysis/AnalysisResultsNewView.js
  app/assets/javascripts/map/views/layers/LossLayer.js
  app/assets/javascripts/services/CountryService.js
  app/controllers/dashboards_controller.rb
  app/javascript/components/map/assets/layers/loss.js
  app/javascript/components/ui/switch/react-toggle.scss
  app/javascript/components/widgets/components/widget-settings/widget-settings-component.jsx
  app/javascript/components/widgets/components/widget-settings/widget-settings-styles.scss
  app/javascript/components/widgets/components/widget/selectors.js
  app/javascript/components/widgets/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions-deforestation/initial-state.js
  app/javascript/components/widgets/widgets/conservation/glad-biodiversity/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-global/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-global/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss/selectors.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/actions.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
  app/javascript/components/widgets/widgets/land-cover/primary-forest/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
  app/javascript/data/forest-types.json
  app/javascript/data/land-categories.json
  app/javascript/pages/dashboards/header/header.js
  app/javascript/providers/country-data-provider/country-data-provider-actions.js
  app/javascript/services/alerts.js
  app/javascript/services/country.js
  app/javascript/services/forest-data.js
  app/javascript/services/geostore.js
  app/javascript/services/total-area.js
  app/javascript/services/whitelists.js
  app/javascript/utils/format.js
  app/javascript/utils/strings.js
  app/models/dashboards.rb
Labels: AWAITING APPROVAL, gadm36, staging

#3488 Feature/lcc widget
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/widgets/land-cover/global-land-cover/actions.js
  app/javascript/components/widgets/widgets/land-cover/global-land-cover/global-land-cover.js
  app/javascript/components/widgets/widgets/land-cover/global-land-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/global-land-cover/selectors.js
  app/javascript/data/colors.json
  app/javascript/data/global-land-cover-categories.json
  app/javascript/services/forest-data.js
Labels: staging
