Repository wri/gfw, pull requests merged in 2018-02, with the labels that each got.

#3277 feature/improve-loss-ticks
  app/javascript/pages/country/widget/widgets/widget-tree-loss/widget-tree-loss-selectors.js
Labels: _DEPLOY, country_pages

#3278 Plantations Extent Widgets
  app/javascript/pages/country/data/colors.json
  app/javascript/pages/country/data/widgets-config.json
  app/javascript/pages/country/widget/widgets/widget-ranked-plantations/widget-ranked-plantations-selectors.js
  app/javascript/pages/country/widget/widgets/widget-tree-cover-plantations/widget-tree-cover-plantations-selectors.js
  app/javascript/services/forest-data.js
Labels: WIP, _DEPLOY, country_pages, fixes

#3283 Updates ranked list label
  app/javascript/pages/country/widget/components/widget-horizontal-bar-chart/custom-tick-component.jsx
Labels: country_pages

#3293 Emissions widget: check for NaN when summing
  app/assets/images/logos-s773785ec1c.png
  app/assets/images/logos-s7d538ad5fe.png
  app/javascript/pages/country/widget/widgets/widget-emissions-deforestation/widget-emissions-deforestation-selectors.js
Labels: bugs, countries

#3295 Updates colours and adds new categories
  app/assets/javascripts/map/templates/legend/bra_mapBiomas.handlebars
  app/assets/javascripts/map/views/layers/BraMapBiomasLayer.js
Labels: _DEPLOY, bra_land_cover, fixes

#3296 Moving Map Biomas Layer into Master
  app/assets/images/logos-s773785ec1c.png
  app/assets/images/logos-s7d538ad5fe.png
  app/assets/javascripts/map/templates/legend/bra_mapBiomas.handlebars
  app/assets/javascripts/map/views/layers/BraMapBiomasLayer.js
  app/javascript/pages/country/widget/widgets/widget-emissions-deforestation/widget-emissions-deforestation-selectors.js
Labels: map

#3297 Fix/glads latest from new endpoint
  app/assets/javascripts/abstract/timeline/TimelineDatePicker.js
  app/assets/javascripts/map/services/GladDateService.js
  app/assets/javascripts/map/views/layers/GladLayer.js
  app/javascript/components/map/assets/layers/glad.js
  app/javascript/pages/country/widget/widgets/widget-glad-alerts/widget-glad-alerts-actions.js
  app/javascript/services/alerts.js
  app/javascript/services/glad.js
Labels: fixes, map

#3300 check for toggled layers in templates and layers
  app/assets/javascripts/map/templates/legend/glad.handlebars
  app/assets/javascripts/map/views/LegendView.js
Labels: fixes, map

#3294 Fix/whitelist for water bodies
  app/javascript/pages/country/providers/country-data-provider/country-data-provider-actions.js
  app/javascript/pages/country/providers/country-data-provider/country-data-provider-reducers.js
  app/javascript/pages/country/providers/country-data-provider/country-data-provider.js
  app/javascript/pages/country/providers/whitelists-provider/whitelists-provider-actions.js
  app/javascript/pages/country/providers/whitelists-provider/whitelists-provider-reducers.js
  app/javascript/pages/country/providers/whitelists-provider/whitelists-provider.js
  app/javascript/pages/country/reducers.js
  app/javascript/pages/country/root/root-component.js
  app/javascript/pages/country/root/root.js
  app/javascript/pages/country/widget/widget-selectors.js
  app/javascript/pages/country/widget/widget.js
  app/javascript/pages/country/widget/widgets/widget-intact-tree-cover/widget-intact-tree-cover-actions.js
  app/javascript/pages/country/widget/widgets/widget-intact-tree-cover/widget-intact-tree-cover.js
  app/javascript/pages/country/widget/widgets/widget-primary-tree-cover/widget-primary-tree-cover-actions.js
  app/javascript/pages/country/widget/widgets/widget-primary-tree-cover/widget-primary-tree-cover.js
  app/javascript/pages/country/widget/widgets/widget-tree-cover-plantations/widget-tree-cover-plantations.js
  app/javascript/pages/country/widget/widgets/widget-tree-cover/widget-tree-cover.js
  app/javascript/services/country.js
  app/javascript/services/whitelists.js
Labels: WIP, countries dashboard

#3302 Feature/ga tracking for pages and actions
  app/javascript/components/button/button-actions.js
  app/javascript/components/button/button-component.jsx
  app/javascript/components/button/button.js
  app/javascript/components/map/components/mini-legend/mini-legend-component.jsx
  app/javascript/components/share/share-component.jsx
  app/javascript/components/share/share-reducers.js
  app/javascript/components/share/share-styles.scss
  app/javascript/components/share/share.js
  app/javascript/pages/country/data/analytics.js
  app/javascript/pages/country/header/header-component.js
  app/javascript/pages/country/index.js
  app/javascript/pages/country/router.js
  app/javascript/pages/country/widget/components/widget-header/widget-header-component.js
  app/javascript/utils/analytics.js
  package.json
Labels: features

#3309 Feature/meta modal updates
  app/assets/stylesheets/modules/_modal_new.scss
  app/javascript/components/modal-meta/modal-meta-styles.scss
  app/javascript/pages/country/data/indicators.json
  app/javascript/pages/country/widget/components/widget-header/widget-header-component.js
  app/javascript/pages/country/widget/components/widget-settings/widget-settings-component.jsx
  app/javascript/pages/country/widget/widget-component.jsx
  app/javascript/pages/country/widget/widget.js
Labels: countries dashboard, map

#3304 Feature/country zoom buttons
  app/javascript/assets/icons/minus.svg
  app/javascript/assets/icons/plus.svg
  app/javascript/components/button/button-component.jsx
  app/javascript/components/icon/icon-component.jsx
  app/javascript/components/icon/icon-styles.scss
  app/javascript/components/map/components/map-controls/map-controls-component.jsx
  app/javascript/components/map/components/map-controls/map-controls-styles.scss
  app/javascript/components/map/components/map-controls/map-controls.js
  app/javascript/components/map/map-actions.js
  app/javascript/components/map/map-component.js
  app/javascript/components/map/map-reducers.js
  app/javascript/components/map/map-styles.scss
  app/javascript/components/map/map.js
  app/javascript/styles/themes/button/button-map-control.scss
Labels: countries dashboard

#3257 Feature/economic impact widget
  app/javascript/pages/country/data/colors.json
  app/javascript/pages/country/data/metrics.json
  app/javascript/pages/country/data/units.json
  app/javascript/pages/country/data/widgets-config.json
  app/javascript/pages/country/reducers.js
  app/javascript/pages/country/widget/components/widget-chart-tooltip/widget-chart-tooltip-component.js
  app/javascript/pages/country/widget/components/widget-composed-chart/custom-tick-component.jsx
  app/javascript/pages/country/widget/components/widget-composed-chart/widget-composed-chart-component.js
  app/javascript/pages/country/widget/components/widget-numbered-list/widget-numbered-list-component.jsx
  app/javascript/pages/country/widget/components/widget-pie-chart/widget-pie-chart-component.js
  app/javascript/pages/country/widget/components/widget-settings/widget-settings-component.jsx
  app/javascript/pages/country/widget/widget-actions.js
  app/javascript/pages/country/widget/widget-component.jsx
  app/javascript/pages/country/widget/widget-selectors.js
  app/javascript/pages/country/widget/widget.js
  app/javascript/pages/country/widget/widgets/widget-economic-impact/widget-economic-impact-actions.js
  app/javascript/pages/country/widget/widgets/widget-economic-impact/widget-economic-impact-component.js
  app/javascript/pages/country/widget/widgets/widget-economic-impact/widget-economic-impact-reducers.js
  app/javascript/pages/country/widget/widgets/widget-economic-impact/widget-economic-impact-selectors.js
  app/javascript/pages/country/widget/widgets/widget-economic-impact/widget-economic-impact-styles.scss
  app/javascript/pages/country/widget/widgets/widget-economic-impact/widget-economic-impact.js
  app/javascript/pages/country/widget/widgets/widget-emissions-deforestation/widget-emissions-deforestation-selectors.js
  app/javascript/pages/country/widget/widgets/widget-emissions/widget-emissions-selectors.js
  app/javascript/pages/country/widget/widgets/widget-ranked-plantations/widget-ranked-plantations-selectors.js
  app/javascript/pages/country/widget/widgets/widget-tree-loss-plantations/widget-tree-loss-plantations-selectors.js
  app/javascript/pages/country/widget/widgets/widget-tree-loss/widget-tree-loss-selectors.js
  app/javascript/utils/format.js
Labels: countries

#3314 feature/fix-image-layer-rescale
  app/javascript/components/map/assets/layers/abstract/image-layer.js
Labels: countries, fixes

#3315 fix/usa-russia-bounds-hack
  app/javascript/pages/country/data/bounds.json
  app/javascript/pages/country/providers/country-data-provider/country-data-provider-actions.js
Labels: countries, fixes
