Repository wri/gfw, pull requests merged in 2018-04, with the labels that each got.

#3357 Fixes percentage calculation bug in Global Loss Rank
  app/javascript/pages/country/widget/widgets/widget-loss-ranked/widget-loss-ranked-selectors.js
Labels: countries, fixes

#3359 Feature/biodiversity layers
  app/assets/javascripts/map/helpers/layersHelper.js
  app/assets/javascripts/map/models/LayerSpecModel.js
  app/assets/javascripts/map/presenters/LayersNavPresenter.js
  app/assets/javascripts/map/presenters/layers/BiodiversityCompletenessLayerPresenter.js
  app/assets/javascripts/map/presenters/layers/BiodiversityIntactnessLayerPresenter.js
  app/assets/javascripts/map/templates/layersNav.handlebars
  app/assets/javascripts/map/templates/legend/biodiversity_completeness.handlebars
  app/assets/javascripts/map/templates/legend/biodiversity_intactness.handlebars
  app/assets/javascripts/map/views/LayersNavView.js
  app/assets/javascripts/map/views/LegendView.js
  app/assets/javascripts/map/views/layers/BiodiversityCompletenessLayer.js
  app/assets/javascripts/map/views/layers/BiodiversityIntactnessLayer.js
  app/assets/stylesheets/modules/map/_module-legend.scss
  bower.json
Labels: staging

#3365 Hides biodiversity layers from PROD temporarily
  app/assets/javascripts/map/templates/layersNav.handlebars
Labels: HOTFIX

#3366 Bugfix/fao widget units
  app/javascript/components/numbered-list/numbered-list-component.jsx
  app/javascript/components/widget/components/widget-settings/widget-settings-component.jsx
  app/javascript/components/widget/widgets/widget-fao-deforestation/widget-fao-deforestation-selectors.js
  app/javascript/components/widget/widgets/widget-fao-reforestation/widget-fao-reforestation-selectors.js
  app/javascript/data/periods.json
Labels: WIP, countries dashboard

#3373 Updates units to 1000s of ha
  app/javascript/services/forest-data.js
Labels: HOTFIX, _DEPLOY, bugs

#3374 Biodiversity Significance Layer 3.0
  app/assets/javascripts/map/templates/layersNav.handlebars
  app/assets/javascripts/map/views/layers/BiodiversityCompletenessLayer.js
Labels: _DEPLOY, layers, map, staging

#3383 SQL Refactor for Global Pages
  app/javascript/services/forest-data.js
Labels: WIP, countries

#3367 GLAD Biodiversity Table Update
  Gemfile.lock
  app/javascript/components/widget/widgets/widget-glad-alerts/widget-glad-alerts-actions.js
  app/javascript/components/widget/widgets/widget-glad-alerts/widget-glad-alerts-selectors.js
  app/javascript/components/widget/widgets/widget-glad-biodiversity/widget-glad-biodiversity-actions.js
  app/javascript/components/widget/widgets/widget-glad-biodiversity/widget-glad-biodiversity-selectors.js
  app/javascript/components/widget/widgets/widget-glad-biodiversity/widget-glad-biodiversity.js
  app/javascript/components/widget/widgets/widget-glad-ranked/widget-glad-ranked-actions.js
  app/javascript/components/widget/widgets/widget-glad-ranked/widget-glad-ranked-selectors.js
  app/javascript/components/widget/widgets/widget-glad-ranked/widget-glad-ranked.js
  app/javascript/services/alerts.js
Labels: countries, features, staging
