Repository wri/gfw, pull requests merged in 2018-05, with the labels that each got.

#3391 Biodiversity Layer Update
  app/assets/javascripts/map/templates/layersNav.handlebars
  app/assets/javascripts/map/templates/legend/biodiversity_completeness.handlebars
  app/assets/javascripts/map/templates/legend/biodiversity_intactness.handlebars
Labels: _DEPLOY

#3396 Updates tree-cover and ifl-cover widgets
  app/javascript/components/widgets/components/widget-header/widget-header-component.js
  app/javascript/components/widgets/widgets/land-cover/fao-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
  app/javascript/pages/dashboards/page/page-selectors.js
Labels: features, global-dashboard

#3397 Indonesian forest area layer update
  app/assets/javascripts/map/cartocss/IdnForestArea.cartocss
  app/assets/javascripts/map/views/layers/IdnForestArea.js
Labels: map, staging

#3400 Feature/fao global
  app/javascript/components/widgets/components/widget/widget.js
  app/javascript/components/widgets/widgets/forest-change/fao-deforest/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/fao-deforest/selectors.js
  app/javascript/components/widgets/widgets/forest-change/fao-reforest/actions.js
  app/javascript/components/widgets/widgets/forest-change/fao-reforest/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/fao-reforest/selectors.js
  app/javascript/services/forest-data.js
Labels: global-dashboard

#3404 Feature/global extent located
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/actions.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
Labels: WIP, global-dashboard

#3405 updated the grid layer for the uncurated places to watch
  app/assets/javascripts/map/views/layers/UncuratedPlaces2WatchLayer.js
Labels: map

#3402 Feature/global gain ranked
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/actions.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
  app/javascript/services/forest-data.js
Labels: global-dashboard

#3407 QA for Tree Cover Widgets
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
Labels: _DEPLOY

#3408 Fixes dynamic sentences for Loss, Gain, Glad.
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
Labels: _DEPLOY

#3410 Fixes global gain widget
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
Labels: HOTFIX, staging

#3409 Hot Fix for global tree cover located
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
Labels: staging

#3412 Fixes Tree-Cover-located widget in all dashboards
  app/javascript/components/widgets/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/actions.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
Labels: staging

#3411 Universal Sentence Formatting
  app/javascript/components/widgets/widgets/climate/emissions/selectors.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-global/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-plantations/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss/selectors.js
  app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
  app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
  app/javascript/components/widgets/widgets/land-cover/ranked-plantations/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover/selectors.js
  app/javascript/components/widgets/widgets/people/economic-impact/selectors.js
  app/javascript/components/widgets/widgets/people/forestry-employment/selectors.js
Labels: staging

#3413 Removes indicators with broken units
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
Labels: HOTFIX, _DEPLOY

#3414 hotfix
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
Labels: HOTFIX, staging

#3415 Default setting for ranked lists
  app/javascript/components/widgets/components/widget-numbered-list/component.jsx
  app/javascript/components/widgets/components/widget/widget.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-gain-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
Labels: staging

#3416 Plantations Extent Sentence
  app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/selectors.js
Labels: staging

#3420 Places2Watch
  app/assets/javascripts/map/views/layers/Places2WatchLayer.js
Labels: _DEPLOY

#3421 Fixes data issue with fao pie chart
  app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
Labels: staging

#3422 Fixes calculations for fao cover
  app/javascript/components/widgets/components/widget/widget.js
  app/javascript/components/widgets/widgets/land-cover/fao-cover/actions.js
  app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
  app/javascript/pages/country/header/header.js
  app/javascript/services/forest-data.js
Labels: HOTFIX, _DEPLOY

#3423 Fao cover pie pt.2
  app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
Labels: _DEPLOY

#3430 Bugfix/nan loss location widget
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-located/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
Labels: bugs

#3433 Updates dynamic sentences and defaults
  app/javascript/components/widgets/widgets/climate/emissions/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/fao-deforest/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/fao-reforest/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/initial-state.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/fao-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
Labels: staging

#3435 Fix - intact & primary widgets
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/actions.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
  app/javascript/components/widgets/widgets/land-cover/primary-forest/actions.js
  app/javascript/components/widgets/widgets/land-cover/primary-forest/initial-state.js
  app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
Labels: staging
