Repository wri/gfw, pull requests merged in 2019-04, with the labels that each got.

#3735 Fixes broken IDN Tree Cover metadata
  app/javascript/components/widgets/components/widget/components/widget-header/selectors.js
Labels: hotfix

#3737 Feature/refetch button
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings-component.js
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery.js
  app/javascript/components/ui/refresh-button/refresh-button-component.jsx
  app/javascript/components/ui/refresh-button/refresh-button-styles.scss
  app/javascript/components/ui/refresh-button/refresh-button.js
  app/javascript/components/widgets/components/widget/component.jsx
  app/javascript/components/widgets/components/widget/index.js
Labels: develop, staging

#3738 Fix/hmr mapbox layer manager
  app/javascript/components/maps/main-map/styles.scss
  app/javascript/components/maps/map/component.jsx
  app/javascript/components/maps/map/components/scale/component.jsx
  app/javascript/components/maps/map/components/scale/index.js
  app/javascript/components/maps/map/components/scale/selectors.js
  app/javascript/components/maps/map/components/scale/styles.scss
  app/javascript/components/maps/map/styles.scss
  package.json
  yarn.lock
Labels: bugfix, develop

#3744 Feature/thank you page
  app/controllers/application_controller.rb
  app/controllers/thankyou_controller.rb
  app/javascript/app/router.js
  app/javascript/pages/thankyou/component.jsx
  app/javascript/pages/thankyou/index.js
  app/javascript/pages/thankyou/styles.scss
  app/views/thankyou/index.html.erb
  config/routes.rb
Labels: develop, staging

#3745 force SSL on all deployed production environments
  config/environments/production.rb
Labels: develop

#3722 Feature: cookies banner
  app/javascript/app/layouts/root/component.jsx
  app/javascript/components/cookies/actions.js
  app/javascript/components/cookies/component.jsx
  app/javascript/components/cookies/index.js
  app/javascript/components/cookies/reducers.js
  app/javascript/components/cookies/styles.scss
  app/javascript/components/modals/welcome/index.js
  app/javascript/components/ui/button/button-styles.scss
  app/javascript/components/ui/button/themes/button-small.scss
  app/javascript/components/ui/button/themes/button-xsmall.scss
  app/javascript/pages/about/section-projects/section-projects.js
Labels: develop, staging

#3746 Update header sentence for IDN
  app/javascript/pages/dashboards/header/header-selectors.js
Labels: hotfix

#3719 Feature: planet basemaps
  app/javascript/components/maps/components/basemaps/basemaps-actions.js
  app/javascript/components/maps/components/basemaps/basemaps-component.jsx
  app/javascript/components/maps/components/basemaps/basemaps-reducers.js
  app/javascript/components/maps/components/basemaps/basemaps-selectors.js
  app/javascript/components/maps/components/basemaps/basemaps.js
  app/javascript/components/maps/components/basemaps/styles.scss
  app/javascript/components/maps/map/basemaps-schema.js
  app/javascript/components/maps/map/selectors.js
  app/javascript/components/ui/dropdown/dropdown-component.jsx
  app/javascript/components/ui/dropdown/themes/dropdown-native-inline.scss
  app/javascript/components/ui/switch/switch-component.jsx
  app/javascript/pages/about/section-projects/section-projects-component.jsx
  app/javascript/services/planet.js
Labels: develop, staging

#3752 Fixed width of analysis 'start drawing' button in map
  app/javascript/components/forms/form-styles.scss
  app/javascript/components/maps/components/analysis/components/chose-analysis/component.jsx
  app/javascript/components/maps/components/analysis/components/chose-analysis/styles.scss
  app/javascript/components/maps/main-map/components/map-controls/map-controls-styles.scss
  app/javascript/components/maps/map/components/popup/component.js
  app/javascript/components/maps/map/components/popup/styles.scss
  app/javascript/components/modals/share/share-styles.scss
Labels: bugfix

#3757 Feature: change default dataset for Fire Alerts widget to VIIRS instead of MODIS
  app/javascript/components/widgets/widgets/forest-change/fires-alerts/settings.js
Labels: develop, staging
