Repository wri/gfw, pull requests merged in 2019-05, with the labels that each got.

#3742 Feature: only show analysis disclaimer when analysing loss and gain
  app/javascript/components/maps/components/analysis/components/show-analysis/component.jsx
  app/javascript/components/maps/components/analysis/components/show-analysis/selectors.js
Labels: develop, staging

#3739 Feature/ui kit modals
  app/javascript/components/modals/attributions/component.jsx
  app/javascript/components/modals/attributions/styles.scss
  app/javascript/components/modals/contact-us/component.jsx
  app/javascript/components/modals/contact-us/styles.scss
  app/javascript/components/modals/loss-disclaimer/component.jsx
  app/javascript/components/modals/loss-disclaimer/styles.scss
  app/javascript/components/modals/meta/meta-component.jsx
  app/javascript/components/modals/meta/meta-styles.scss
  app/javascript/components/modals/modal/modal-component.jsx
  app/javascript/components/modals/modal/modal-styles.scss
  app/javascript/components/modals/share/share-component.jsx
  app/javascript/components/modals/share/share-styles.scss
  app/javascript/components/modals/sources/component.jsx
  app/javascript/components/modals/sources/config.js
  app/javascript/components/modals/sources/styles.scss
  app/javascript/components/modals/subscribe/component.jsx
  app/javascript/components/modals/subscribe/styles.scss
  app/javascript/components/modals/video/video-component.jsx
  app/javascript/components/modals/video/video-styles.scss
  app/javascript/components/modals/welcome/component.jsx
  app/javascript/components/modals/welcome/styles.scss
  app/javascript/components/ui/switch/switch-component.jsx
  app/javascript/pages/about/section-projects/section-projects-modal/section-projects-modal-styles.scss
  app/javascript/pages/sgf/section-projects/section-projects-modal/section-projects-modal-component.jsx
  app/javascript/pages/sgf/section-projects/section-projects-modal/section-projects-modal-styles.scss
  app/javascript/styles/settings.scss
Labels: develop

#3759 Info icons on map search working correctly
  app/javascript/components/maps/components/menu/components/sections/search/index.js
Labels: bugfix

#3763 Removed GFW water
  app/assets/javascripts/static/ContactUsView.js
  app/assets/javascripts/static/helpers/applicationsHelper.js
  app/views/shared/icons/_svg_icons.html.erb
  app/views/shared/icons/_svg_icons_home.html.erb
Labels: develop

#3760 Removed sitemap components and mentions
  app/assets/javascripts/views/HeaderView.js
  app/assets/stylesheets/layouts/_sitemap.scss
  app/assets/stylesheets/sitemap.scss
  app/controllers/sitemap_controller.rb
  app/javascript/components/footer/footer-component.jsx
  app/javascript/components/footer/footer-styles.scss
  app/javascript/components/header/components/submenu-panel/component.jsx
  app/views/sitemap/index.html.erb
  config/routes.rb
  config/sitemap.rb
  spec/controllers/sitemap_controller_spec.rb
Labels: develop

#3741 Feature: roads selector in basemap settings
  app/javascript/components/maps/components/basemaps/basemaps-component.jsx
  app/javascript/components/maps/components/basemaps/basemaps-selectors.js
  app/javascript/components/maps/components/basemaps/basemaps.js
  app/javascript/components/maps/map/basemaps-schema.js
  app/javascript/components/maps/map/component.jsx
  app/javascript/components/maps/map/reducers.js
  app/javascript/components/maps/map/selectors.js
  app/javascript/components/modals/welcome/styles.scss
  app/javascript/pages/topics/vendors/scrolloverflow.min.js
Labels: develop

#3764 Feature/update seo metadata
  app/controllers/application_controller.rb
  app/controllers/connect_controller.rb
  app/controllers/landing_controller.rb
  app/controllers/search_controller.rb
  app/controllers/static_controller.rb
  app/javascript/app/layouts/root/selectors.js
  app/javascript/components/widgets/selectors.js
Labels: develop

#3758 Feature/trase widget
  .env.prod.sample
  .env.sample
  app/javascript/components/ui/dynamic-sentence/dynamic-sentence-styles.scss
  app/javascript/components/widgets/components/widget/component.jsx
  app/javascript/components/widgets/components/widget/components/widget-header/components/widget-settings/widget-settings-component.jsx
  app/javascript/components/widgets/components/widget/index.js
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/widgets/land-use/economic-impact/config.js
  app/javascript/components/widgets/widgets/land-use/forestry-employment/config.js
  app/javascript/components/widgets/widgets/land-use/trase-commodities/actions.js
  app/javascript/components/widgets/widgets/land-use/trase-commodities/component.jsx
  app/javascript/components/widgets/widgets/land-use/trase-commodities/config.js
  app/javascript/components/widgets/widgets/land-use/trase-commodities/index.js
  app/javascript/components/widgets/widgets/land-use/trase-commodities/selectors.js
  app/javascript/components/widgets/widgets/land-use/trase-commodities/settings.js
  app/javascript/components/widgets/widgets/land-use/trase-commodities/styles.scss
  app/javascript/components/world-map/component.jsx
  app/javascript/components/world-map/index.js
  app/javascript/components/world-map/selectors.js
  app/javascript/components/world-map/style.scss
  app/javascript/data/WORLD.topo.json
  app/javascript/data/units.json
  app/javascript/pages/dashboards/header/header-actions.js
  app/javascript/services/trase.js
  package.json
  yarn.lock
Labels: awaiting feedback, develop, staging

#3765 Fix/intact primary sentence
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
  app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
Labels: deploy

#3767 Changed frequency in the PTW description
  app/javascript/components/maps/components/menu/components/sections/explore/explore-sections.js
Labels: bugfix

#3768 Small change to dynamic sentence
  app/javascript/components/widgets/widgets/forest-change/tree-loss/config.js
Labels: bugfix

#3770 Fix: recent imagery infinite fetching thumbs
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings-component.js
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-actions.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-selectors.js
  app/javascript/services/recent-imagery.js
Labels: develop, hotfix

#3773 Fix/glad analysis
  app/javascript/components/map/assets/layers/glad.js
  app/javascript/components/widgets/widgets/forest-change/glad-alerts/actions.js
  app/javascript/components/widgets/widgets/forest-change/glad-ranked/actions.js
  app/javascript/services/alerts.js
Labels: bugfix, hotfix

#3766 Fixed percentage numbers over 100
  app/javascript/components/widgets/widgets/climate/cumulative-emissions/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
Labels: bugfix

#3771 Fixing analytics events through the page
  app/javascript/analytics/map.js
  app/javascript/analytics/shared.js
  app/javascript/components/cookies/component.jsx
  app/javascript/components/map/components/mini-legend/mini-legend-component.jsx
  app/javascript/components/maps/components/analysis/component.jsx
  app/javascript/components/maps/map/index.js
  app/javascript/components/ui/button/button-component.jsx
  app/javascript/components/widgets/components/widget/components/widget-footer/component.jsx
Labels: develop

#3750 Feature/ui kit map settings menu
  app/javascript/components/maps/components/basemaps/basemaps-component.jsx
  app/javascript/components/maps/components/basemaps/basemaps-selectors.js
  app/javascript/components/maps/components/basemaps/styles.scss
  app/javascript/components/maps/components/menu/components/sections/datasets/categories-menu/component.jsx
  app/javascript/components/maps/components/menu/components/sections/datasets/categories-menu/styles.scss
  app/javascript/components/maps/components/menu/components/sections/datasets/component.jsx
  app/javascript/components/maps/components/menu/components/sections/datasets/dataset-section/styles.scss
  app/javascript/components/maps/components/menu/components/sections/datasets/styles.scss
  app/javascript/components/maps/components/menu/menu-sections.js
  app/javascript/components/maps/main-map/components/map-controls/map-controls-component.jsx
  app/javascript/components/maps/main-map/components/map-controls/map-controls-selectors.js
  app/javascript/components/maps/main-map/components/map-controls/map-controls-styles.scss
  app/javascript/components/maps/map/basemaps-schema.js
  app/javascript/components/maps/map/component.jsx
  app/javascript/components/ui/button/button-component.jsx
  app/javascript/components/ui/button/themes/button-dark-round.scss
  app/javascript/components/ui/dropdown/components/item/styles.scss
  app/javascript/components/ui/dropdown/components/menu/component.jsx
  app/javascript/components/ui/dropdown/components/menu/styles.scss
  app/javascript/components/ui/dropdown/components/selector/component.jsx
  app/javascript/components/ui/dropdown/dropdown-component.jsx
  app/javascript/components/ui/dropdown/themes/dropdown-dark-round.scss
  app/javascript/components/ui/dropdown/themes/dropdown-dark-squared.scss
  app/javascript/components/ui/dropdown/themes/dropdown-native-inline.scss
  app/javascript/components/ui/dropdown/themes/dropdown-no-border.scss
  app/views/shared/_sources_map.html.erb
Labels: develop
