Repository wri/gfw, pull requests merged in 2019-01, with the labels that each got.

#3682 Fix/format the latest fetched date for forma
  app/javascript/components/maps/components/menu/components/sections/datasets/component.jsx
  app/javascript/components/maps/map/selectors.js
  app/javascript/providers/datasets-provider/datasets-utils.js
Labels: develop, hotfix

#3683 Fix/only show perm separator statement when present
  app/javascript/components/widgets/widgets/forest-change/tree-loss-tsc/selectors.js
Labels: develop, hotfix

#3684 Feature/update hompage cards
  app/assets/images/home/card-0.png
  app/assets/images/home/card-0@2x.jpg
  app/assets/images/home/card-1.png
  app/assets/images/home/card-1@2x.jpg
  app/assets/images/home/card-2.png
  app/assets/images/home/card-2@2x.jpg
  app/assets/images/home/card-3.png
  app/assets/images/home/card-3@2x.jpg
  app/assets/images/home/card-4.png
  app/assets/images/home/card-4@2x.jpg
  app/assets/stylesheets/components/home/_c-home-summary.scss
  app/controllers/landing_controller.rb
  app/views/landing/_summary.html.erb
Labels: develop, staging

#3685 Add new icons for map menu
  app/javascript/assets/icons/biodiversity.svg
  app/javascript/assets/icons/boundaries.svg
  app/javascript/assets/icons/climate.svg
  app/javascript/assets/icons/explore.svg
  app/javascript/assets/icons/forest-change.svg
  app/javascript/assets/icons/labels.svg
  app/javascript/assets/icons/land-cover.svg
  app/javascript/assets/icons/land-use.svg
  app/javascript/assets/icons/roads.svg
  app/javascript/components/maps/main-map/components/map-controls/map-controls-component.jsx
  app/javascript/components/maps/main-map/components/map-tour/component.jsx
  app/javascript/pages/dashboards/header/header-selectors.js
  app/javascript/providers/country-data-provider/actions.js
Labels: develop

#3688 Fix/bug fixes for bugs
  app/javascript/assets/icons/biodiversity.svg
  app/javascript/assets/icons/climate.svg
  app/javascript/assets/icons/explore.svg
  app/javascript/assets/icons/forest-change.svg
  app/javascript/assets/icons/land-cover.svg
  app/javascript/assets/icons/land-use.svg
  app/javascript/components/maps/components/menu/menu-component.jsx
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery.js
  app/javascript/components/modals/meta/meta-actions.js
  app/javascript/components/modals/modal/modal-component.jsx
  app/javascript/providers/country-data-provider/actions.js
  app/javascript/providers/geostore-provider/actions.js
  app/javascript/providers/ptw-provider/actions.js
  app/javascript/providers/whitelists-provider/whitelists-provider-actions.js
Labels: hotfix

#3679 Feature/donut plot
  app/assets/stylesheets/components/home/_c-home-summary.scss
  app/javascript/components/charts/components/pie-chart-legend/pie-chart-legend-component.jsx
  app/javascript/components/widgets/components/widget/selectors.js
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/widgets/climate/emissions-deforestation/config.js
  app/javascript/components/widgets/widgets/climate/emissions-deforestation/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/actions.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/config.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/index.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/settings.js
  app/javascript/data/colors.json
  app/javascript/services/forest-data.js
Labels: develop, staging

#3690 Fix/issues with recent imagery fetches
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-actions.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-selectors.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery.js
  app/javascript/components/ui/datepicker/datepicker-styles.scss
Labels: develop, hotfix

#3689 Fix/redirect user to profile if empty
  app/javascript/components/modals/subscribe/components/subscription-form/styles.scss
  app/javascript/providers/mygfw-provider/actions.js
Labels: develop, hotfix

#3699 Update map decode config inline with dashboard version
  app/javascript/providers/datasets-provider/datasets-decode-config.js
  yarn.lock
Labels: hotfix

#3695 Fixed units in the graph to show more detail
  app/javascript/components/widgets/widgets/climate/emissions-plantations/selectors.js
Labels: staging

#3698 Feature/grants fellowship page
  app/controllers/application_controller.rb
  app/controllers/grants_and_fellowships_controller.rb
  app/controllers/small_grants_fund_controller.rb
  app/javascript/app/router.js
  app/javascript/components/header/config.js
  app/javascript/pages/sgf/component.jsx
  app/javascript/pages/sgf/section-about/img/GFW_TECH_logo.png
  app/javascript/pages/sgf/section-about/section-about-component.jsx
  app/javascript/pages/sgf/section-about/section-about-styles.scss
  app/javascript/pages/sgf/section-about/section-about.js
  app/javascript/pages/sgf/section-apply/img/GFW_TECH_logo.png
  app/javascript/pages/sgf/section-apply/section-apply-component.jsx
  app/javascript/pages/sgf/section-apply/section-apply-styles.scss
  app/javascript/pages/sgf/section-projects/section-projects-component.jsx
  app/javascript/pages/sgf/section-projects/section-projects.js
  app/views/grants_and_fellowships/index.html.erb
  config/routes.rb
  config/sitemap.rb
  spec/controllers/small_funds_grant_controller_spec.rb
Labels: develop

#3697 Fixes value mismatch in sentence and graph axis label, and units issu…
  app/javascript/components/charts/composed-chart/composed-chart-component.js
  app/javascript/components/widgets/widgets/climate/future-carbon-gains/selectors.js
Labels: staging
