Repository wri/gfw, pull requests merged in 2019-06, with the labels that each got.

#3777 Feature/commodities to pro
  app/assets/images/home/pro.png
  app/assets/images/home/pro@2x.png
  app/assets/stylesheets/components/home/_c-home-applications.scss
  app/assets/stylesheets/layouts/_static.scss
  app/javascript/assets/icons/gfw-pro.svg
  app/javascript/assets/logos/gfw-pro.png
  app/javascript/components/forms/contact/contact-component.jsx
  app/javascript/components/header/config.js
  app/javascript/pages/home/assets/commodities@2x.jpg
  app/javascript/pages/home/assets/pro-bg.png
  app/javascript/pages/home/assets/pro-bg@2x.png
  app/javascript/pages/home/component.jsx
  app/javascript/pages/home/config.js
  app/javascript/pages/home/styles.scss
  app/javascript/pages/topics/assets/commodities/cards/pro.png
  app/javascript/pages/topics/assets/commodities/cards/pro@2x.png
  app/javascript/pages/topics/config/commodities.js
  app/views/shared/icons/_svg_icons_home.html.erb
Labels: develop

#3789 move locationLevelToStr to utils, fixed TSC for geostores and high zoom levels
  app/javascript/components/analysis/components/show-analysis/selectors.js
  app/javascript/components/analysis/selectors.js
  app/javascript/components/widgets/selectors.js
  app/javascript/utils/format.js
Labels: bugfix

#3788 Added custom class to avoid body scroll when header menu is open
  app/javascript/components/header/components/nav-alt/component.jsx
  app/javascript/components/header/components/nav-alt/styles.scss
Labels: bugfix

#3740 Feature/all carbon widget
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/widgets/climate/carbon-stock/actions.js
  app/javascript/components/widgets/widgets/climate/carbon-stock/config.js
  app/javascript/components/widgets/widgets/climate/carbon-stock/index.js
  app/javascript/components/widgets/widgets/climate/carbon-stock/selectors.js
  app/javascript/components/widgets/widgets/climate/carbon-stock/settings.js
  app/javascript/components/widgets/widgets/climate/emissions-deforestation/config.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/config.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions/config.js
  app/javascript/components/widgets/widgets/climate/soil-organic/selectors.js
  app/javascript/components/widgets/widgets/climate/whrc-biomass/selectors.js
  app/javascript/data/colors.json
  app/javascript/data/variables.json
  app/javascript/utils/calculations.js
Labels: develop, staging
