Repository wri/gfw, pull requests merged in 2019-02, with the labels that each got.

#3700 Fixed mixed http/https in climate indicators, now using carto
  app/javascript/components/widgets/widgets/climate/future-carbon-gains/actions.js
  app/javascript/components/widgets/widgets/climate/future-carbon-gains/config.js
  app/javascript/services/climate.js
Labels: hotfix

#3691 Feature/recent imagery interactions update
  app/javascript/components/maps/components/menu/components/menu-panel/component.jsx
  app/javascript/components/maps/components/menu/components/menu-panel/styles.scss
  app/javascript/components/maps/components/menu/menu-component.jsx
  app/javascript/components/maps/components/menu/menu-sections.js
  app/javascript/components/maps/components/menu/menu-selectors.js
  app/javascript/components/maps/components/menu/menu.js
  app/javascript/components/maps/main-map/component.jsx
  app/javascript/components/maps/main-map/components/data-analysis-menu/component.jsx
  app/javascript/components/maps/main-map/components/map-controls/map-controls-component.jsx
  app/javascript/components/maps/main-map/components/map-controls/map-controls-styles.scss
  app/javascript/components/maps/main-map/components/map-controls/map-controls.js
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings-tooltip/component.jsx
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings-tooltip/index.js
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings-component.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-actions.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-reducers.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery-selectors.js
  app/javascript/components/maps/main-map/components/recent-imagery/recent-imagery.js
  app/javascript/components/maps/main-map/index.js
  app/javascript/components/maps/main-map/initial-state.js
  app/javascript/components/maps/main-map/selectors.js
  app/javascript/components/maps/main-map/styles.scss
  app/javascript/components/maps/map/component.jsx
  app/javascript/components/maps/map/selectors.js
  app/javascript/components/ui/loader/loader-component.js
  app/javascript/components/ui/loader/loader-styles.scss
  app/javascript/styles/settings.scss
Labels: develop, staging

#3703 Feature/updated grants and fellows
  app/javascript/assets/icons/markers/marker_fellow.png
  app/javascript/assets/icons/markers/marker_fellow.svg
  app/javascript/assets/icons/markers/marker_fellow@2x.png
  app/javascript/assets/icons/markers/marker_grantee.png
  app/javascript/assets/icons/markers/marker_grantee.svg
  app/javascript/assets/icons/markers/marker_grantee@2x.png
  app/javascript/components/globe/globe-component.jsx
  app/javascript/components/globe/globe-styles.scss
  app/javascript/components/ui/card/card-component.jsx
  app/javascript/components/ui/card/card-styles.scss
  app/javascript/pages/about/section-projects/section-projects-component.jsx
  app/javascript/pages/sgf/section-projects/section-projects-component.jsx
  app/javascript/pages/sgf/section-projects/section-projects-modal/section-projects-modal-actions.js
  app/javascript/pages/sgf/section-projects/section-projects-modal/section-projects-modal-component.jsx
  app/javascript/pages/sgf/section-projects/section-projects-modal/section-projects-modal-reducers.js
  app/javascript/pages/sgf/section-projects/section-projects-modal/section-projects-modal-styles.scss
  app/javascript/pages/sgf/section-projects/section-projects-modal/section-projects-modal.js
  app/javascript/pages/sgf/section-projects/section-projects-styles.scss
  app/javascript/pages/sgf/section-projects/section-projects.js
Labels: staging

#3677 Feature/whrc biomass widget (simple sentence)
  app/javascript/components/numbered-list/numbered-list-component.jsx
  app/javascript/components/widgets/components/widget/component.jsx
  app/javascript/components/widgets/components/widget/components/widget-header/components/widget-settings/widget-settings-component.jsx
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/options.js
  app/javascript/components/widgets/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions-deforestation/config.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/config.js
  app/javascript/components/widgets/widgets/climate/future-carbon-gains/config.js
  app/javascript/components/widgets/widgets/climate/whrc-biomass/actions.js
  app/javascript/components/widgets/widgets/climate/whrc-biomass/config.js
  app/javascript/components/widgets/widgets/climate/whrc-biomass/index.js
  app/javascript/components/widgets/widgets/climate/whrc-biomass/selectors.js
  app/javascript/components/widgets/widgets/climate/whrc-biomass/settings.js
  app/javascript/data/colors.json
  app/javascript/data/variables.json
  app/javascript/services/climate.js
Labels: develop, staging

#3692 Feature/cumulative emissions widget
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/utils/data.js
  app/javascript/components/widgets/widgets/climate/cumulative-emissions/actions.js
  app/javascript/components/widgets/widgets/climate/cumulative-emissions/config.js
  app/javascript/components/widgets/widgets/climate/cumulative-emissions/index.js
  app/javascript/components/widgets/widgets/climate/cumulative-emissions/selectors.js
  app/javascript/components/widgets/widgets/climate/cumulative-emissions/settings.js
  app/javascript/data/variables.json
  app/javascript/services/climate.js
Labels: develop, staging

#3706 Feature/soil organic carbon
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/widgets/climate/soil-organic/actions.js
  app/javascript/components/widgets/widgets/climate/soil-organic/config.js
  app/javascript/components/widgets/widgets/climate/soil-organic/index.js
  app/javascript/components/widgets/widgets/climate/soil-organic/selectors.js
  app/javascript/components/widgets/widgets/climate/soil-organic/settings.js
  app/javascript/components/widgets/widgets/climate/whrc-biomass/config.js
  app/javascript/services/climate.js
Labels: staging

#3707 Fix: Ranked gain widget parent location
  app/javascript/components/widgets/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions-plantations/selectors.js
  app/javascript/components/widgets/widgets/climate/emissions/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/config.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-loss-ranked/selectors.js
  app/javascript/components/widgets/widgets/land-cover/fao-cover/selectors.js
  app/javascript/components/widgets/widgets/land-cover/intact-tree-cover/selectors.js
  app/javascript/components/widgets/widgets/land-cover/primary-forest/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-located/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-plantations/selectors.js
  app/javascript/components/widgets/widgets/land-cover/tree-cover-ranked/selectors.js
  app/javascript/components/widgets/widgets/land-use/economic-impact/selectors.js
  app/javascript/components/widgets/widgets/land-use/forestry-employment/selectors.js
Labels: hotfix
