Repository wri/gfw, pull requests merged in 2019-03, with the labels that each got.

#3705 Feature/metadata modal url
  app/javascript/components/maps/components/legend/components/layer-list-menu/component.jsx
  app/javascript/components/maps/components/legend/components/layer-toggle/component.jsx
  app/javascript/components/maps/components/legend/legend.js
  app/javascript/components/maps/components/menu/components/sections/datasets/component.jsx
  app/javascript/components/maps/components/menu/components/sections/datasets/index.js
  app/javascript/components/maps/components/menu/menu-component.jsx
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings-component.js
  app/javascript/components/maps/main-map/components/recent-imagery/components/recent-imagery-settings/recent-imagery-settings.js
  app/javascript/components/modals/meta/meta-actions.js
  app/javascript/components/modals/meta/meta-component.jsx
  app/javascript/components/modals/meta/meta-reducers.js
  app/javascript/components/modals/meta/meta.js
  app/javascript/components/modals/sources/component.jsx
  app/javascript/components/modals/subscribe/component.jsx
  app/javascript/components/modals/subscribe/components/subscription-form/component.jsx
  app/javascript/components/modals/subscribe/index.js
  app/javascript/components/ui/dropdown/components/item/component.jsx
  app/javascript/components/widgets/components/widget/components/widget-header/component.js
  app/javascript/components/widgets/components/widget/components/widget-header/components/widget-settings/widget-settings-component.jsx
  app/javascript/components/widgets/components/widget/components/widget-header/index.js
  app/javascript/pages/sgf/section-projects/section-projects-modal/section-projects-modal-component.jsx
Labels: staging

#3702 GFW 4.0: MapboxGL + Vector Plantations Layer
  app/javascript/app/index.js
  app/javascript/assets/logos/mapbox-logo-white.svg
  app/javascript/components/maps/components/analysis/selectors.js
  app/javascript/components/maps/components/menu/components/sections/explore/explore-sections.js
  app/javascript/components/maps/components/menu/components/sections/explore/explore-selectors.js
  app/javascript/components/maps/main-map/components/data-analysis-menu/component.jsx
  app/javascript/components/maps/main-map/components/data-analysis-menu/index.js
  app/javascript/components/maps/main-map/components/map-controls/map-controls-component.jsx
  app/javascript/components/maps/main-map/index.js
  app/javascript/components/maps/main-map/selectors.js
  app/javascript/components/maps/map/basemaps-schema.js
  app/javascript/components/maps/map/component.jsx
  app/javascript/components/maps/map/components/draw/actions.js
  app/javascript/components/maps/map/components/draw/config.js
  app/javascript/components/maps/map/components/draw/index.js
  app/javascript/components/maps/map/components/layer-manager/component.jsx
  app/javascript/components/maps/map/components/layer-manager/selectors.js
  app/javascript/components/maps/map/components/map-attributions/component.jsx
  app/javascript/components/maps/map/components/map-attributions/styles.scss
  app/javascript/components/maps/map/components/popup/component.js
  app/javascript/components/maps/map/components/popup/components/data-table/styles.scss
  app/javascript/components/maps/map/components/popup/popup.js
  app/javascript/components/maps/map/components/popup/reducers.js
  app/javascript/components/maps/map/components/popup/selectors.js
  app/javascript/components/maps/map/components/popup/styles.scss
  app/javascript/components/maps/map/index.js
  app/javascript/components/maps/map/reducers.js
  app/javascript/components/maps/map/selectors.js
  app/javascript/components/maps/map/styles.scss
  app/javascript/components/widgets/components/widget/components/widget-header/selectors.js
  app/javascript/components/widgets/widgets/forest-change/tree-cover-gain/selectors.js
  app/javascript/providers/datasets-provider/datasets-decode-config.js
  app/javascript/providers/datasets-provider/datasets-provider-actions.js
  app/javascript/providers/whitelists-provider/whitelists-provider.js
  app/javascript/services/analysis.js
  app/javascript/services/geostore.js
  app/javascript/utils/dates.js
  app/javascript/utils/format.js
  app/views/shared/_leaflet.html.erb
  package.json
  yarn.lock
Labels: develop, staging

#3713 Added anchor links to sections in SGF About tab
  app/javascript/pages/sgf/section-about/section-about-component.jsx
Labels: staging

#3718 Added basemap metadata info button to the tooltip
  app/javascript/components/maps/components/basemaps/basemaps-component.jsx
  app/javascript/components/maps/components/basemaps/basemaps.js
  app/javascript/components/maps/components/basemaps/styles.scss
Labels: develop

#3716 Fixed an issue with the datepicker dropdowns showing the wrong month
  app/javascript/components/ui/datepicker/datepicker-component.js
Labels: bugfix

#3717 Updated GLAD alerts widget with new whitelist
  app/javascript/components/widgets/widgets/forest-change/glad-alerts/config.js
Labels: develop

#3730 Fix: increase scroll to speed for sgf about tab
  app/javascript/components/scroll-to/scroll-to.js
  app/javascript/pages/sgf/section-about/section-about-component.jsx
Labels: develop

#3729 Feature: add contact us to header
  app/javascript/components/footer/footer-component.jsx
  app/javascript/components/header/component.jsx
  app/javascript/components/header/components/submenu-panel/component.jsx
  app/javascript/components/header/components/submenu-panel/styles.scss
  app/javascript/components/header/index.js
Labels: develop

#3725 Feature: add responsive map attributions and mobile info modal
  app/javascript/assets/logos/mapbox-logo-white.svg
  app/javascript/assets/logos/mapbox.svg
  app/javascript/components/maps/main-map/component.jsx
  app/javascript/components/maps/main-map/styles.scss
  app/javascript/components/maps/map/component.jsx
  app/javascript/components/maps/map/components/map-attributions/component.jsx
  app/javascript/components/maps/map/components/map-attributions/index.js
  app/javascript/components/maps/map/components/map-attributions/styles.scss
  app/javascript/components/maps/map/styles.scss
  app/javascript/components/modals/attributions/actions.js
  app/javascript/components/modals/attributions/component.jsx
  app/javascript/components/modals/attributions/index.js
  app/javascript/components/modals/attributions/reducers.js
  app/javascript/components/modals/attributions/styles.scss
  app/javascript/components/modals/sources/component.jsx
Labels: develop, staging
