Repository wri/gfw, pull requests merged in 2020-11, with the labels that each got.

#4124 Calculate ext difference
  components/widgets/forest-change/tree-loss-pct/selectors.js
Labels: deploy

#4114 Feature/tree height decode
  providers/datasets-provider/config.js
Labels: develop

#4109 Feature/PRODES vector layer
  components/map/selectors.js
Labels: WIP

#4135 Remove widget from manifest
  components/widgets/manifest.js
Labels: deploy

#4133 Update decode for easier reading
  providers/datasets-provider/config.js
Labels: develop
