Repository wri/gfw, pull requests merged in 2020-06, with the labels that each got.

#3982 TCL 2019 & Primary Loss
  app/javascript/components/charts/components/chart-tooltip/chart-tooltip-component.js
  app/javascript/components/charts/components/chart-tooltip/chart-tooltip-styles.scss
  app/javascript/components/charts/composed-chart/composed-chart-component.jsx
  app/javascript/components/ui/dynamic-sentence/dynamic-sentence-component.jsx
  app/javascript/components/ui/dynamic-sentence/dynamic-sentence-styles.scss
  app/javascript/components/widgets/climate/emissions-deforestation/index.js
  app/javascript/components/widgets/climate/emissions-deforestation/selectors.js
  app/javascript/components/widgets/forest-change/fires-ranked/index.js
  app/javascript/components/widgets/forest-change/glad-ranked/index.js
  app/javascript/components/widgets/forest-change/tree-loss-located/index.js
  app/javascript/components/widgets/forest-change/tree-loss-pct/index.js
  app/javascript/components/widgets/forest-change/tree-loss-pct/selectors.js
  app/javascript/components/widgets/forest-change/tree-loss-plantations/index.js
  app/javascript/components/widgets/forest-change/tree-loss-plantations/selectors.js
  app/javascript/components/widgets/forest-change/tree-loss-ranked/index.js
  app/javascript/components/widgets/forest-change/tree-loss-tsc/index.js
  app/javascript/components/widgets/forest-change/tree-loss/index.js
  app/javascript/components/widgets/forest-change/tree-loss/selectors.js
  app/javascript/components/widgets/land-cover/tree-cover-located/index.js
  app/javascript/components/widgets/land-cover/tree-cover-ranked/index.js
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/selectors.js
  app/javascript/components/widgets/utils/config.js
  app/javascript/components/widgets/utils/data.js
  app/javascript/data/analysis-datasets.json
  app/javascript/data/colors.json
  app/javascript/data/forest-types.js
  app/javascript/data/land-categories.js
  app/javascript/data/layers-datasets.js
  app/javascript/data/layers.js
  app/javascript/pages/dashboards/component.jsx
  app/javascript/providers/geodescriber-provider/selectors.js
  app/javascript/providers/whitelists-provider/actions.js
  app/javascript/services/analysis-cached.js
  app/javascript/utils/format.js
Labels: TCL 2019, develop

#4006 Alphabetically sorted aois.
  app/javascript/components/map-menu/components/sections/my-gfw/component.jsx
  app/javascript/pages/my-gfw/components/areas-table/component.jsx
  app/javascript/providers/areas-provider/selectors.js
Labels: bugfix

#4010 Fix/order tooltip by values using a sortBy tooltip config key.
  app/javascript/components/charts/components/chart-tooltip/component.jsx
  app/javascript/components/charts/composed-chart/component.jsx
  app/javascript/components/widgets/fires/fires-alerts-cumulative/selectors.js
Labels: bugfix

#4015 Add uppercase key to land categories
  app/javascript/components/widgets/forest-change/glad-alerts/index.js
  app/javascript/components/widgets/utils/config.js
  app/javascript/data/land-categories.js
  app/javascript/utils/format.js
Labels: deploy

#4007 Feat/update primary loss
  app/javascript/components/widgets/forest-change/tree-loss-pct/index.js
  app/javascript/components/widgets/forest-change/tree-loss-pct/selectors.js
  app/javascript/components/widgets/utils/config.js
Labels: TCL 2019, awaiting feedback

#4008 Feat/fires widgets feedback
  Gemfile.lock
  app/javascript/components/charts/lollipop-chart/component.jsx
  app/javascript/components/widgets/fires/fires-alerts-cumulative/index.js
  app/javascript/components/widgets/fires/fires-alerts-cumulative/selectors.js
  app/javascript/components/widgets/fires/fires-alerts-historical-daily/index.js
  app/javascript/components/widgets/fires/fires-alerts-historical-daily/selectors.js
  app/javascript/components/widgets/fires/fires-alerts-historical/index.js
  app/javascript/components/widgets/fires/fires-alerts-historical/selectors.js
  app/javascript/components/widgets/fires/fires-alerts/index.js
  app/javascript/components/widgets/fires/fires-alerts/selectors.js
  app/javascript/components/widgets/fires/fires-ranked/index.js
  app/javascript/components/widgets/fires/fires-ranked/selectors.js
  app/javascript/components/widgets/fires/fires-within/index.js
  app/javascript/components/widgets/fires/fires-within/selectors.js
  app/javascript/data/colors.json
  app/javascript/data/units.json
  app/javascript/services/analysis-cached.js
  app/javascript/utils/data.js
  app/javascript/utils/format.js
  docs/yarn.lock
  yarn.lock
Labels: WIP, fires-widgets

#4020 Improve sort of fire season dates
  app/javascript/components/widgets/fires/fires-alerts/selectors.js
Labels: develop

#4022 Point to correct column
  app/javascript/data/land-categories.js
Labels: deploy

#4019 Fix / unitless pct lollipops
  app/javascript/components/charts/lollipop-chart/component.jsx
Labels: bugfix

#4023 Added days to the xAxis ticks on the firesAlertsHistorical widget.
  app/javascript/components/widgets/fires/fires-alerts-historical/selectors.js
Labels: bugfix

#4025 Adds primary forest to map for primary loss widget
  app/javascript/components/widgets/forest-change/tree-loss-pct/index.js
Labels: deploy

#4026 remove metakey
  app/javascript/data/datasets.json
Labels: develop, fires-widgets

#4029 Adds primary forest to dashboard on add to map
  app/javascript/components/widgets/forest-change/tree-loss-pct/index.js
Labels: deploy

#4030 Reorder fire tab
  app/javascript/components/widgets/fires/fires-alerts-cumulative/index.js
  app/javascript/components/widgets/fires/fires-alerts-historical-old/index.js
  app/javascript/components/widgets/fires/fires-alerts-historical/index.js
  app/javascript/components/widgets/fires/fires-ranked/index.js
  app/javascript/components/widgets/fires/fires-within/index.js
Labels: fires-widgets

#4021 Feat/climate widgets to tables
  app/javascript/components/widget/component.jsx
  app/javascript/components/widget/components/widget-pie-chart-legend/component.jsx
  app/javascript/components/widgets/climate/carbon-stock/index.js
  app/javascript/components/widgets/climate/carbon-stock/selectors.js
  app/javascript/components/widgets/climate/whrc-biomass/index.js
  app/javascript/components/widgets/climate/whrc-biomass/selectors.js
  app/javascript/data/units.json
  app/javascript/services/analysis-cached.js
  app/javascript/services/climate.js
  app/javascript/utils/calculations.js
Labels: deploy
