Repository wri/gfw, pull requests merged in 2020-04, with the labels that each got.

#3927 updating language pre-aoi launch
  app/javascript/components/analysis/components/show-analysis/component.jsx
Labels: deploy

#3959 Added check for subsector in save AOI modal
  app/javascript/components/forms/profile/component.jsx
  app/javascript/components/modals/area-of-interest/component.jsx
Labels: bugfix

#3963 Fix version
  app/javascript/components/widgets/climate/emissions-deforestation/index.js
Labels: bugfix, deploy

#3965 Feat/landmark to prod
  app/javascript/components/widgets/climate/emissions-deforestation/index.js
  app/javascript/components/widgets/land-cover/tree-cover-located/selectors.js
  app/javascript/components/widgets/land-cover/tree-cover-ranked/selectors.js
  app/javascript/data/land-categories.json
Labels: deploy
