Repository wri/gfw, pull requests merged in 2020-01, with the labels that each got.

#3668 Feature: bio intactness widget
  app/javascript/components/charts/composed-chart/composed-chart-component.jsx
  app/javascript/components/charts/composed-chart/custom-background-component.jsx
  app/javascript/components/charts/composed-chart/custom-tick-component.jsx
  app/javascript/components/modals/meta/meta-component.jsx
  app/javascript/components/modals/share/share-component.jsx
  app/javascript/components/paginate/paginate-component.js
  app/javascript/components/widgets/components/widget-chart-and-list/component.jsx
  app/javascript/components/widgets/components/widget-chart-and-list/index.js
  app/javascript/components/widgets/components/widget-chart-and-list/styles.scss
  app/javascript/components/widgets/components/widget-composed-chart/component.jsx
  app/javascript/components/widgets/components/widget-numbered-list/component.jsx
  app/javascript/components/widgets/components/widget/components/widget-header/components/widget-settings/widget-settings-component.jsx
  app/javascript/components/widgets/components/widget/index.js
  app/javascript/components/widgets/manifest.js
  app/javascript/components/widgets/options.js
  app/javascript/components/widgets/selectors.js
  app/javascript/components/widgets/styles.scss
  app/javascript/components/widgets/widgets/biodiversity/intactness/actions.js
  app/javascript/components/widgets/widgets/biodiversity/intactness/config.js
  app/javascript/components/widgets/widgets/biodiversity/intactness/index.js
  app/javascript/components/widgets/widgets/biodiversity/intactness/percentiles.json
  app/javascript/components/widgets/widgets/biodiversity/intactness/selectors.js
  app/javascript/components/widgets/widgets/biodiversity/intactness/settings.js
  app/javascript/data/biodiversity-int.json
  app/javascript/data/colors.json
Labels: WIP, awaiting feedback, staging

#3736 Feature/ptw commodities layer
  app/assets/images/layer-icons/ptw-mongabay.svg
  app/assets/images/layer-icons/ptw-palm-oil.svg
  app/assets/images/layer-icons/ptw-soy.svg
  app/javascript/components/map-menu/components/sections/explore/component.jsx
  app/javascript/components/map-menu/components/sections/explore/selectors.js
  app/javascript/components/map-menu/components/sections/explore/styles.scss
  app/javascript/components/map-menu/reducers.js
  app/javascript/components/map-menu/selectors.js
  app/javascript/components/map/components/legend/component.jsx
  app/javascript/components/map/components/legend/components/layer-list-menu/component.jsx
  app/javascript/components/map/components/legend/components/layer-list-menu/styles.scss
  app/javascript/components/map/components/legend/components/layer-toggle/styles.scss
  app/javascript/components/map/components/legend/themes/vizzuality-legend.scss
  app/javascript/components/map/components/popup/selectors.js
  app/javascript/components/map/components/popup/styles.scss
  app/javascript/components/modals/meta/component.jsx
  app/javascript/components/modals/share/share-component.jsx
  app/javascript/components/ui/card/card-component.jsx
  app/javascript/components/ui/card/card-styles.scss
  app/javascript/components/ui/card/themes/card-small.scss
  app/javascript/pages/sgf/section-projects/section-projects-component.jsx
  app/javascript/providers/ptw-provider/actions.js
  app/javascript/services/places-to-watch.js
Labels: develop

#3891 Feature/enable email login
  app/javascript/components/modals/subscribe/component.jsx
  app/javascript/components/modals/subscribe/styles.scss
  app/javascript/pages/my-gfw/component.jsx
Labels: feature flag
