Repository wri/gfw, pull requests merged in 2020-09, with the labels that each got.

#4078 WIP decode function for RADD
  providers/datasets-provider/config.js
Labels: map

#4079 Feat/radd decode
  providers/datasets-provider/config.js
Labels: develop

#4084 Filter 2001 fromo totals
  components/widgets/forest-change/tree-loss-pct/selectors.js
Labels: deploy

#4057 Bump loss by driver year
  components/widgets/forest-change/tree-loss-tsc/index.js
Labels: deploy

#4087 Bump TCL by Driver year
  components/widgets/forest-change/tree-loss-tsc/index.js
Labels: develop

#4089 basemap fix
  .env.sample
  app.json
  components/basemaps/component.jsx
  components/basemaps/selectors.js
  components/map/basemaps.js
  components/map/components/attributions/component.jsx
  layouts/about/section-partners/index.js
  layouts/map/component.jsx
  providers/planet-provider/actions.js
  providers/planet-provider/index.js
  providers/planet-provider/reducers.js
  services/planet.js
  utils/stateToUrl.js
Labels: deploy
