Repository wri/gfw, pull requests merged in 2020-07, with the labels that each got.

#4037 Feature/remove planet basemaps
  app/javascript/components/map/basemaps.js
  app/javascript/components/map/component.jsx
  app/javascript/components/modals/planet-notice/actions.js
  app/javascript/components/modals/planet-notice/component.jsx
  app/javascript/components/modals/planet-notice/index.js
  app/javascript/components/modals/planet-notice/styles.scss
  app/javascript/components/modals/sources/config.js
  app/javascript/pages/map/component.jsx
  app/javascript/providers/planet-provider/actions.js
  app/javascript/providers/planet-provider/index.js
  app/javascript/providers/planet-provider/reducers.js
  app/javascript/utils/stateToUrl.js
Labels: WIP, awaiting approval

#4039 Feature/remove feature flags for fires
  app/javascript/app/layouts/root/component.jsx
  app/javascript/app/router.js
  app/javascript/components/aoi-card/component.jsx
  app/javascript/components/header/config.js
  app/javascript/components/widgets/forest-change/fires-alerts/index.js
  app/javascript/components/widgets/forest-change/fires-alerts/selectors.js
  app/javascript/components/widgets/forest-change/fires-ranked/index.js
  app/javascript/components/widgets/forest-change/fires-ranked/selectors.js
  app/javascript/components/widgets/forest-change/fires/index.js
  app/javascript/components/widgets/forest-change/fires/selectors.js
  app/javascript/components/widgets/manifest.js
  app/javascript/pages/dashboards/selectors.js
Labels: awaiting approval, fires

#4044 Grabs correct week range
  app/javascript/services/analysis-cached.js
Labels: fires-widgets

#4045 Hotfix/fires ranked sql
  app/javascript/components/widgets/fires/fires-ranked/selectors.js
Labels: deploy, fires-widgets

#4036 Feature/remove old fires
  app/javascript/components/header/config.js
  app/javascript/pages/home/config.js
Labels: fires

#4038 Feature/add monthly summary field back to areas form
  app/javascript/components/forms/area-of-interest/component.jsx
Labels: awaiting approval

#4049 Update status calculation to match visualisation
  app/javascript/components/widgets/fires/fires-alerts-cumulative/selectors.js
Labels: deploy

#4050 Account for period that overlaps years
  components/widgets/fires/fires-ranked/selectors.js
  services/analysis-cached.js
Labels: deploy, fires-widgets

#4053 Feat/add test tab
  components/map-menu/sections.js
Labels: deploy

#4055 Reimplement carbon equations
  components/widgets/climate/whrc-biomass/index.js
  utils/calculations.js
Labels: deploy

#4059 Change year order to capture seasons across year
  components/widgets/fires/fires-alerts/selectors.js
Labels: deploy
