Repository wri/gfw, pull requests merged in 2021-06, with the labels that each got.

#4250 Sum over isos
  components/widgets/land-cover/intact-tree-cover/index.js
  components/widgets/land-cover/tree-cover/index.js
Labels: hotfix

#4251 Fix header
  providers/geodescriber-provider/actions.js
Labels: deploy

#4258 Fix metadata labels
  components/widgets/fires/fires-ranked/selectors.js
Labels: deploy

#4241 add api key support for data api
  .env.sample
  pages/api/data-api/[...params].js
  pages/api/gfw-api/[...params].js
  services/analysis-cached.js
  services/otf-analysis.js
  utils/apis.js
  utils/request.js
  utils/url.js
Labels: blocked
