Repository wri/gfw, pull requests merged in 2021-07, with the labels that each got.

#4262 Final touches to burned areas widgets
  components/widgets/fires/burned-area-cumulative/index.js
  components/widgets/fires/burned-area-cumulative/selectors.js
  components/widgets/fires/burned-area-ranked/index.js
  components/widgets/fires/burned-area-ranked/selectors.js
  components/widgets/fires/burned-area/index.js
  components/widgets/fires/burned-area/selectors.js
  components/widgets/fires/fire-alerts-simple/index.js
  components/widgets/fires/fires-alerts-historical-weekly/index.js
  components/widgets/manifest.js
  data/forest-types.js
Labels: develop, ready to review

#4264 Fix missing week-53 when comparing years
  components/widgets/fires/burned-area/selectors.js
  components/widgets/fires/fires-alerts/selectors.js
Labels: develop, ready to review

#4252 Change RW API domain to api.resourcewatch.org
  components/analysis/actions.js
  components/map/basemaps.js
  components/widget/components/widget-header/components/widget-download-button/component.jsx
  components/widgets/reducers.js
  cypress/fixtures/otf_spec.json
  cypress/fixtures/widgets_spec.json
  cypress/integration/otf.js
  cypress/integration/widget.js
  cypress/utils/init-spec-file.js
  docs/backup/configs/production/044f4af8-be72-4999-b7dd-13434fc4a394.json
  docs/backup/configs/production/098b33df-6871-4e53-a5ff-b56a7d989f9a.json
  docs/backup/configs/production/134caa0a-21f7-451d-a7fe-30db31a424aa.json
  docs/backup/configs/production/13e28550-3fc9-45ec-bb00-5a48a82b77e1.json
  docs/backup/configs/production/3a8e0ae1-fcc5-4a50-abd1-37f158f173ec.json
  docs/backup/configs/production/4316b45c-e744-4f4c-9823-142eb7638c8d.json
  docs/backup/configs/production/461e6f3f-c03c-40b2-8a40-47d1354c93bf.json
  docs/backup/configs/production/5da0c609-c20c-4e99-9d2c-3b1120a2983b.json
  docs/backup/configs/production/68c81bc5-171c-4425-9836-d45659f0ed23.json
  docs/backup/configs/production/714339c1-c775-4303-aad4-16d975b2f023.json
  docs/backup/configs/production/81c802aa-5feb-4fbe-9986-8f30c0597c4d.json
  docs/backup/configs/production/85f82851-e16e-4126-a630-93bb63d4ef42.json
  docs/backup/configs/production/897ecc76-2308-4c51-aeb3-495de0bdca79.json
  docs/backup/configs/production/8d59a30f-9537-44ff-a6ca-29cf5c62a607.json
  docs/backup/configs/production/a481466d-de8a-450c-b792-271901d20d3b.json
  docs/backup/configs/production/b3fa1221-db2a-4826-95a1-37ac0973cc4b.json
  docs/backup/configs/production/bd5d7924-611e-4302-9185-8054acb0b44b.json
  docs/backup/configs/production/bfd1d211-8106-4393-86c3-9e1ab2ee1b9b.json
  docs/backup/configs/production/d7b12b17-9ed4-43ab-b8e4-efa2668c47f8.json
  docs/backup/configs/production/e663eb09-04de-4f39-b871-35c6c2ed10b5.json
  docs/backup/configs/production/fe8b5f03-0ff9-4c18-ba39-77dcfe69908f.json
  docs/backup/configs/staging/4839cc85-a4fe-41e5-96fd-51796aa694a6.json
  docs/backup/configs/staging/e663eb09-04de-4f39-b871-35c6c2ed10b5.json
  package.json
  services/analysis-cached.js
  services/climate.js
  services/otf-analysis.js
  utils/apis.js
  utils/request.js
  yarn.lock
Labels: preprod

#4259 Reveal simple glad alerts widget
  components/widget/components/widget-header/components/widget-download-button/component.jsx
  components/widgets/forest-change/glad-alerts-simple/index.js
  components/widgets/manifest.js
  services/analysis-cached.js
Labels: WIP

#4276 Add flux widget
  components/analysis/components/show-analysis/styles.scss
  components/widgets/climate/carbon-flux/index.js
  components/widgets/climate/emissions-deforestation/index.js
  data/datasets.js
  data/layers.js
  services/analysis-cached.js
Labels: deploy

#4286 Feat/vocabulary env splitting
  providers/datasets-provider/actions.js
  services/datasets.js
Labels: deploy
