Repository wri/gfw, pull requests merged in 2021-01, with the labels that each got.

#4151 Update palette, make code more readable
  providers/datasets-provider/config.js
Labels: develop

#4156 update of SGF page for 2021
  layouts/grants-and-fellowships/apply/component.jsx
Labels: awaiting approval

#4159 fixing primary forest loss widget
  components/widgets/forest-change/tree-loss-pct/selectors.js
  components/widgets/manifest.js
Labels: bugfix, deploy
