Repository wri/gfw, pull requests merged in 2021-02, with the labels that each got.

#4170 removing esa land cover widget
  components/widgets/manifest.js
Labels: awaiting approval, feature

#4171 Fix seasonStartDate issue
  components/widgets/fires/fires-alerts/selectors.js
Labels: deploy

#4174 Fall back to default date if latest is in the future
  providers/latest-provider/actions.js
Labels: hotfix

#4176 Hotfix/fires dates
  components/widgets/fires/fires-alerts/index.js
  components/widgets/fires/fires-alerts/selectors.js
Labels: deploy
